Repository astrochun/Zcalbase_gal, pull requests merged in 2021-02, with the labels that each got.

#77 76__move_get_det3
  analysis/deep2_r23_o32/__init__.py
  analysis/deep2_r23_o32/archives/Extra_functions_not_in_use.py
  analysis/deep2_r23_o32/archives/plotting/SN_graphs.py
  analysis/deep2_r23_o32/archives/refactor_into_msc/individual_detection2.py
  analysis/deep2_r23_o32/archives/test_gaussian_stack.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
Labels: enhancement, organization

#73 Feature/docstring -> develop
  analysis/deep2_r23_o32/binning/double_binning_grid.py
  analysis/deep2_r23_o32/binning/fixed_grid_analysis.py
  analysis/deep2_r23_o32/binning/n_bins_grid_analysis.py
  analysis/deep2_r23_o32/binning/single_grid_o32.py
  analysis/deep2_r23_o32/binning/single_grid_r23.py
  analysis/deep2_r23_o32/calibration_plots.py
  analysis/deep2_r23_o32/construct_master_grid.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/log_commons.py
  analysis/deep2_r23_o32/plotting/color_bin_plotting.py
  analysis/deep2_r23_o32/plotting/histogram_plots.py
  analysis/deep2_r23_o32/plotting/line_ratio_plotting.py
  analysis/deep2_r23_o32/plotting/manual_bin_grid.py
  analysis/deep2_r23_o32/plotting/more_plots.py
  analysis/deep2_r23_o32/plotting/te_metal_plots.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
  analysis/green_peas_calibration.py
  analysis/local_analog_calibration.py
Labels: enhancement

#78 release/v0.11.0
  analysis/deep2_r23_o32/__init__.py
  analysis/deep2_r23_o32/archives/Extra_functions_not_in_use.py
  analysis/deep2_r23_o32/archives/plotting/SN_graphs.py
  analysis/deep2_r23_o32/archives/refactor_into_msc/individual_detection2.py
  analysis/deep2_r23_o32/archives/test_gaussian_stack.py
  analysis/deep2_r23_o32/binning/double_binning_grid.py
  analysis/deep2_r23_o32/binning/fixed_grid_analysis.py
  analysis/deep2_r23_o32/binning/n_bins_grid_analysis.py
  analysis/deep2_r23_o32/binning/single_grid_o32.py
  analysis/deep2_r23_o32/binning/single_grid_r23.py
  analysis/deep2_r23_o32/calibration_plots.py
  analysis/deep2_r23_o32/construct_master_grid.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/log_commons.py
  analysis/deep2_r23_o32/plotting/color_bin_plotting.py
  analysis/deep2_r23_o32/plotting/histogram_plots.py
  analysis/deep2_r23_o32/plotting/line_ratio_plotting.py
  analysis/deep2_r23_o32/plotting/manual_bin_grid.py
  analysis/deep2_r23_o32/plotting/more_plots.py
  analysis/deep2_r23_o32/plotting/te_metal_plots.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
  analysis/green_peas_calibration.py
  analysis/local_analog_calibration.py
Labels: Analysis, enhancement, refactor

#83 Simplify Zcalbase_gal imports in relative manner
  analysis/deep2_r23_o32/__init__.py
  analysis/deep2_r23_o32/plotting/more_plots.py
Labels: enhancement, organization, refactor

#82 Remove unused imports in all modules
  analysis/deep2_r23_o32/binning/n_bins_grid_analysis.py
  analysis/deep2_r23_o32/binning/single_grid_o32.py
  analysis/deep2_r23_o32/binning/single_grid_r23.py
  analysis/deep2_r23_o32/calibration_plots.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/plotting/line_ratio_plotting.py
  analysis/deep2_r23_o32/plotting/more_plots.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
  analysis/green_peas_calibration.py
Labels: enhancement, refactor

#90 feature/89_add_graph_to_bin_file
  analysis/deep2_r23_o32/binning/n_bins_grid_analysis.py
  analysis/deep2_r23_o32/plotting/manual_bin_grid.py
Labels: Plotting, enhancement

#87 feature/86_add_paper_bool
  analysis/deep2_r23_o32/binning/n_bins_grid_analysis.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
Labels: enhancement

#92 hotfix/v0.11.1
  analysis/deep2_r23_o32/log_commons.py
Labels: bug

#93 release/v0.12.0
  analysis/deep2_r23_o32/__init__.py
  analysis/deep2_r23_o32/binning/n_bins_grid_analysis.py
  analysis/deep2_r23_o32/binning/single_grid_o32.py
  analysis/deep2_r23_o32/binning/single_grid_r23.py
  analysis/deep2_r23_o32/calibration_plots.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/plotting/line_ratio_plotting.py
  analysis/deep2_r23_o32/plotting/manual_bin_grid.py
  analysis/deep2_r23_o32/plotting/more_plots.py
  analysis/deep2_r23_o32/run_general_script.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
  analysis/green_peas_calibration.py
Labels: enhancement

#84 Simplify variable namespace
  analysis/deep2_r23_o32/Zcal_calibration.py
  analysis/deep2_r23_o32/__init__.py
  analysis/deep2_r23_o32/archives/binning/Binning_and_Graphing.py
  analysis/deep2_r23_o32/archives/binning/binning_and_graphing_mastergrid.py
  analysis/deep2_r23_o32/archives/binning_redshift.py
  analysis/deep2_r23_o32/archives/plotting/SN_graphs.py
  analysis/deep2_r23_o32/archives/plotting/balmer_plots.py
  analysis/deep2_r23_o32/archives/refactor_into_msc/individual_detect.py
  analysis/deep2_r23_o32/archives/refactor_into_msc/individual_detection2.py
  analysis/deep2_r23_o32/archives/run_functions/voronoi_general.py
  analysis/deep2_r23_o32/binning/double_binning_grid.py
  analysis/deep2_r23_o32/binning/fixed_grid_analysis.py
  analysis/deep2_r23_o32/binning/n_bins_grid_analysis.py
  analysis/deep2_r23_o32/binning/single_grid_o32.py
  analysis/deep2_r23_o32/binning/single_grid_r23.py
  analysis/deep2_r23_o32/calibration_plots.py
  analysis/deep2_r23_o32/construct_master_grid.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/plotting/color_bin_plotting.py
  analysis/deep2_r23_o32/plotting/histogram_plots.py
  analysis/deep2_r23_o32/plotting/line_ratio_plotting.py
  analysis/deep2_r23_o32/plotting/manual_bin_grid.py
  analysis/deep2_r23_o32/plotting/more_plots.py
  analysis/deep2_r23_o32/plotting/te_metal_plots.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
  analysis/green_peas_calibration.py
  observing/find_nearby_bright_star.py
Labels: enhancement, organization, refactor
