Repository astrochun/Zcalbase_gal, pull requests merged in 2021-01, with the labels that each got.

#53 feature/commons_folder_structure -> develop
  analysis/deep2_r23_o32/archives/hstack_tables.py
  analysis/deep2_r23_o32/calibration_plots.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/plotting/more_plots.py
  analysis/deep2_r23_o32/plotting/te_metal_plots.py
  analysis/deep2_r23_o32/run_general_script.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
  analysis/green_peas_calibration.py
Labels: enhancement

#63 Merging feature/commons_folder_structure to feature/57_logging
  .github/workflows/create-release.yml
  __init__.py
  analysis/deep2_r23_o32/Zcal_calibration.py
  analysis/deep2_r23_o32/__init__.py
  analysis/deep2_r23_o32/archives/balmer_test.py
  analysis/deep2_r23_o32/archives/binning/binning_and_graphing_mastergrid.py
  analysis/deep2_r23_o32/archives/binning_redshift.py
  analysis/deep2_r23_o32/archives/hstack_tables.py
  analysis/deep2_r23_o32/archives/refactor_into_msc/dust_attenuation_functions.py
  analysis/deep2_r23_o32/archives/refactor_into_msc/get_det3_function.py
  analysis/deep2_r23_o32/archives/run_functions/double_bin_general.py
  analysis/deep2_r23_o32/archives/run_functions/voronoi_general.py
  analysis/deep2_r23_o32/binning/double_binning_grid.py
  analysis/deep2_r23_o32/binning/fixed_grid_analysis.py
  analysis/deep2_r23_o32/calibration_plots.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/plotting/color_bin_plotting.py
  analysis/deep2_r23_o32/plotting/histogram_plots.py
  analysis/deep2_r23_o32/plotting/line_ratio_plotting.py
  analysis/deep2_r23_o32/plotting/more_plots.py
  analysis/deep2_r23_o32/plotting/te_metal_plots.py
  analysis/deep2_r23_o32/run_general_script.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
  analysis/green_peas_calibration.py
  analysis/line_widths.py
Labels: enhancement, organization, refactor

#58 feature/57_logging
  analysis/deep2_r23_o32/Zcal_calibration.py
  analysis/deep2_r23_o32/binning/double_binning_grid.py
  analysis/deep2_r23_o32/binning/fixed_grid_analysis.py
  analysis/deep2_r23_o32/binning/n_bins_grid_analysis.py
  analysis/deep2_r23_o32/binning/single_grid_o32.py
  analysis/deep2_r23_o32/binning/single_grid_r23.py
  analysis/deep2_r23_o32/calibration_plots.py
  analysis/deep2_r23_o32/construct_master_grid.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/log_commons.py
  analysis/deep2_r23_o32/plotting/color_bin_plotting.py
  analysis/deep2_r23_o32/plotting/te_metal_plots.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
  analysis/green_peas_calibration.py
  analysis/local_analog_calibration.py
Labels: enhancement, refactor

#69 release/v0.10.0
  analysis/deep2_r23_o32/Zcal_calibration.py
  analysis/deep2_r23_o32/__init__.py
  analysis/deep2_r23_o32/archives/hstack_tables.py
  analysis/deep2_r23_o32/archives/line_widths.py
  analysis/deep2_r23_o32/archives/refactor_into_msc/r_temp_calcul.py
  analysis/deep2_r23_o32/binning/double_binning_grid.py
  analysis/deep2_r23_o32/binning/fixed_grid_analysis.py
  analysis/deep2_r23_o32/binning/n_bins_grid_analysis.py
  analysis/deep2_r23_o32/binning/single_grid_o32.py
  analysis/deep2_r23_o32/binning/single_grid_r23.py
  analysis/deep2_r23_o32/calibration_plots.py
  analysis/deep2_r23_o32/construct_master_grid.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/log_commons.py
  analysis/deep2_r23_o32/plotting/color_bin_plotting.py
  analysis/deep2_r23_o32/plotting/more_plots.py
  analysis/deep2_r23_o32/plotting/te_metal_plots.py
  analysis/deep2_r23_o32/run_general_script.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
  analysis/green_peas_calibration.py
  analysis/local_analog_calibration.py
Labels: Analysis, Plotting, enhancement, organization, refactor

#71 hotfix/v0.10.1
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
Labels: enhancement, refactor

#75 72_handlestack2d -> develop
  analysis/deep2_r23_o32/__init__.py
  analysis/deep2_r23_o32/general.py
  analysis/deep2_r23_o32/stackboth_mastergrid.py
  analysis/deep2_r23_o32/zoom_and_gauss_general.py
Labels: enhancement
